version: '3.7'
services:
  db:
    image: mysql:5.7
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project
      MYSQL_USER: project
      MYSQL_PASSWORD: project
    volumes:
      - ./database:/docker-entrypoint-initdb.d
  php:
    build: ./php-fpm
    ports:
      - "9000:9001"
    volumes:
      - ./backend:/var/www/project
      - ./logs/php:/var/log/php
    links:
      - db
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    links:
      - php
    volumes:
      - ./backend:/var/www/project
      - ./logs/nginx:/var/log/nginx
  node:
    build: ./node
    ports:
      - "3000:3000"
    links:
      - php
    volumes:
      - ./frontend:/var/www/frontend
      - ./logs/node:/var/log/node
